### ISSUE TITLE
Implementing session for user login

### ISSUE THREAD

**Issue by gustianh** [gustianh/examonline#2]
I'm beginning to build a login session system. Currently I've create a new controller on 
https://github.com/gustianh/examonline/commit/97a04a0bd1a206403f33f54c1b72dd546e62c4f6

Proposed changes are:

- [ ] Implement login page with user leveling (based on database design)
- [ ] Implement session to all controllers (login checking)
- [ ] Implement session management (login/logout)

**Comment by fahminlb33** [comment]
This is not really an issue so I had to make a few changes to this thread.

1. The title is misleading, use more direct topic as title.
2. The content of the first thread is not helpful, add more details.
3. Add metas to this issue, for example add Labes and Assignee.
